save_path: saved_kl4_bsz12_acc2_lr4.5e6

model:
  base_learning_rate: 4.5e-06
  target: latent_diffusion.ldm.models.autoencoder.AutoencoderKL
  params:
    monitor: val/rec_loss
    embed_dim: 4
    lossconfig:
      target: latent_diffusion.ldm.modules.losses.contperceptual.LPIPSWithDiscriminator
      params:
        disc_start: 50001
        kl_weight: 0.000001
        disc_weight: 0.5

    ddconfig:
      double_z: true
      z_channels: 4
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 2
      - 4
      - 4
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0

data:
  target: data.data_processing.datasets.DataModule
  params:
    batch_size: 12
    num_workers: 4
    wrap: false
    shuffle: true
    drop_last: true
    pin_memory: true
    prefetch_factor: 2
    persistent_workers: true
    train:
      target: data.data_processing.datasets.ActionsData
      params:
        data_csv_path: train_dataset/train_dataset_14frames_firstframe_allframes_ae.csv
    # validation:
    #   target: data.data_processing.datasets.ActionsData
    #   params:
    #     data_csv_path: /u4/jlrivard/CSLLM/computer/train_dataset/train_dataset.csv

lightning:
  trainer:
    benchmark: True
    max_epochs: 1
    limit_val_batches: 0
    accelerator: gpu
    devices: 1
    accumulate_grad_batches: 2 
