model:
  base_learning_rate: 4.5e-06
  target: latent_diffusion.ldm.models.autoencoder.VQModel
  params:
    embed_dim: 3
    n_embed: 8192
    monitor: val/rec_loss

    ddconfig:
      double_z: false
      z_channels: 3
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0
    lossconfig:
      target: latent_diffusion.ldm.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: false
        disc_in_channels: 3
        disc_start: 0
        disc_weight: 0.75
        codebook_weight: 1.0

data:
  target: data.data_processing.datasets.DataModule
  params:
    batch_size: 16
    num_workers: 4
    wrap: false
    shuffle: true
    drop_last: true
    pin_memory: true
    prefetch_factor: 2
    persistent_workers: true
    train:
      target: data.data_processing.datasets.ActionsData
      params:
        data_csv_path: /u4/jlrivard/CSLLM/computer/train_dataset_1000_videos/train_dataset.csv
    validation:
      target: data.data_processing.datasets.ActionsData
      params:
        data_csv_path: /u4/jlrivard/CSLLM/computer/train_dataset_1000_videos/train_dataset.csv

lightning:
  trainer:
    benchmark: false
    max_epochs: 1
    limit_val_batches: 0
    accelerator: cuda
    devices: 2
    strategy: ddp_find_unused_parameters_true
    precision: 32-true