save_path: saved_vq8_bsz8_acc1_lr1e6_loadtrainer

model:
  base_learning_rate: 1.0e-06
  target: latent_diffusion.ldm.models.autoencoder.VQModel
  params:
    embed_dim: 4
    n_embed: 16384
    monitor: val/rec_loss

    ddconfig:
      double_z: false
      z_channels: 4
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 2
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions:
      - 32
      dropout: 0.0
    lossconfig:
      target: latent_diffusion.ldm.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: false
        disc_in_channels: 3
        disc_num_layers: 2
        disc_start: 1
        disc_weight: 0.6
        codebook_weight: 1.0
data:
  target: data.data_processing.datasets.DataModule
  params:
    batch_size: 8
    num_workers: 4
    wrap: false
    shuffle: true
    drop_last: true
    pin_memory: true
    prefetch_factor: 2
    persistent_workers: true
    train:
      target: data.data_processing.datasets.ActionsData
      params:
        data_csv_path: train_dataset/train_dataset_14frames_firstframe_allframes_ae.csv
    # validation:
    #   target: data.data_processing.datasets.ActionsData
    #   params:
    #     data_csv_path: /u4/jlrivard/CSLLM/computer/train_dataset/train_dataset.csv

lightning:
  trainer:
    benchmark: False
    max_epochs: 3
    limit_val_batches: 0
    accelerator: gpu
    gpus: 1
