save_path: /root/computer/computer/train_dataset_encoded/saved_final_hs4096_oc32_nl48_ar_cm1_2_mc512_lr8e5_b64_gpu8_filtered_largeimg_cont4_lr8e5_b50_context8_b80_all_fixrelu_simplifyinput_debug_pretrain21

model:
  base_learning_rate: 8e-05
  target: latent_diffusion.ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    pretrain: True
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: action_
    scheduler_sampling_rate: 0.0
    hybrid_key: c_concat
    image_size: [64, 48]
    channels: 3
    cond_stage_trainable: false
    conditioning_key: hybrid
    monitor: val/loss_simple_ema

    unet_config:
      target: latent_diffusion.ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: [64, 48]
        in_channels: 48
        out_channels: 16
        model_channels: 512
        attention_resolutions: []
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        num_head_channels: 32
        use_spatial_transformer: false
        transformer_depth: 1

    temporal_encoder_config:
      target: latent_diffusion.ldm.modules.encoders.temporal_encoder.TemporalEncoder
      params:
        input_channels: 16
        hidden_size: 4096
        num_layers: 1
        dropout: 0.1
        output_channels: 32
        output_height: 48
        output_width: 64

    first_stage_config:
      target: latent_diffusion.ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 16
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 16
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config: __is_unconditional__

data:
  target: data.data_processing.datasets.DataModule
  params:
    batch_size: 80
    num_workers: 8
    wrap: false
    shuffle: True
    drop_last: True
    pin_memory: True
    prefetch_factor: 2
    persistent_workers: True
    train:
      target: data.data_processing.datasets.ActionsData
      params:
        #data_csv_path: ../data/data_processing/train_dataset/filtered_dataset.target_frames.clustered.train.csv
        debug_mode: True
        data_csv_path: ../data/data_processing/train_dataset/train_dataset.target_frames.train.csv
        normalization: standard
        context_length: 8

lightning:
  trainer:
    benchmark: True
    max_epochs: 64000
    limit_val_batches: 0
    accelerator: gpu
    devices: 1
    strategy: ddp_find_unused_parameters_false
    accumulate_grad_batches: 1
    gradient_clip_val: 1
