save_path: saved_standard_challenging_context32_nocond_fixnorm_all_scheduled_sampling_0.2_feedz_comb0.1_rnn_fixrnn_enablegrad_all_keyevent_a_hs4096_oc32_nl48_ar_cm1_2_3_mc320

model:
  base_learning_rate: 8.0e-05
  target: latent_diffusion.ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: action_
    scheduler_sampling_rate: 0.0
    hybrid_key: c_concat
    image_size: [64, 48]
    channels: 3
    cond_stage_trainable: false
    conditioning_key: hybrid
    monitor: val/loss_simple_ema

    unet_config:
      target: latent_diffusion.ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: [64, 48]
        in_channels: 48
        out_channels: 16
        model_channels: 320
        attention_resolutions: []
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 3
        num_head_channels: 32
        use_spatial_transformer: false
        transformer_depth: 1

    temporal_encoder_config:
      target: latent_diffusion.ldm.modules.encoders.temporal_encoder.TemporalEncoder
      params:
        input_channels: 16
        hidden_size: 4096
        num_layers: 1
        dropout: 0.1
        output_channels: 32
        output_height: 48
        output_width: 64

    first_stage_config:
      target: latent_diffusion.ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 16
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 16
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config: __is_unconditional__

data:
  target: data.data_processing.datasets.DataModule
  params:
    batch_size: 64
    num_workers: 4
    wrap: false
    shuffle: True
    drop_last: True
    pin_memory: True
    prefetch_factor: 2
    persistent_workers: True
    train:
      target: data.data_processing.datasets.ActionsData
      params:
        data_csv_path: ../data/data_processing/train_dataset/filtered_dataset.target_frames.clustered.train.csv
        normalization: standard
        context_length: 32
        #validation:
        #  target: data.data_processing.datasets.ActionsData
        #  params:
        #    data_csv_path: train_dataset/train_dataset_14frames_firstframe_allframes.csv

lightning:
  trainer:
    benchmark: False
    max_epochs: 6400
    limit_val_batches: 0
    accelerator: gpu
    gpus: 1
    accumulate_grad_batches: 1
    gradient_clip_val: 1
    checkpoint_callback: True 
