data:
  params:
    batch_size: 8
    drop_last: true
    num_workers: 4
    persistent_workers: true
    pin_memory: true
    prefetch_factor: 2
    shuffle: true
    train:
      params:
        context_length: 4
        data_csv_path: desktop_sequences_filtered_with_desktop_1.5k.challenging.train.target_frames.csv
        normalization: standard
      target: data.data_processing.datasets.ActionsData
    wrap: false
  target: data.data_processing.datasets.DataModule
lightning:
  trainer:
    accelerator: gpu
    accumulate_grad_batches: 99999999
    benchmark: false
    checkpoint_callback: true
    gpus: 1
    gradient_clip_val: 1
    limit_val_batches: 0
    max_epochs: 6400
model:
  base_learning_rate: 8.0e-05
  params:
    channels: 3
    cond_stage_config:
      params:
        n_embed: 768
        n_layer: 12
      target: latent_diffusion.ldm.modules.encoders.modules.GPTEmbedder
    cond_stage_key: action_
    cond_stage_trainable: true
    conditioning_key: hybrid
    first_stage_config:
      params:
        ddconfig:
          attn_resolutions: []
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          double_z: true
          dropout: 0.0
          in_channels: 3
          num_res_blocks: 2
          out_ch: 3
          resolution: 256
          z_channels: 4
        embed_dim: 4
        lossconfig:
          target: torch.nn.Identity
        monitor: val/rec_loss
      target: latent_diffusion.ldm.models.autoencoder.AutoencoderKL
    first_stage_key: image
    hybrid_key: c_concat
    image_size:
    - 64
    - 48
    linear_end: 0.0195
    linear_start: 0.0015
    log_every_t: 200
    monitor: val/loss_simple_ema
    num_timesteps_cond: 1
    scheduler_sampling_rate: 0.0
    timesteps: 1000
    unet_config:
      params:
        attention_resolutions:
        - 8
        - 4
        - 2
        channel_mult:
        - 1
        - 2
        - 3
        - 5
        context_dim: 768
        image_size:
        - 64
        - 48
        in_channels: 26
        model_channels: 192
        num_head_channels: 32
        num_res_blocks: 2
        out_channels: 4
        transformer_depth: 1
        use_spatial_transformer: true
      target: latent_diffusion.ldm.modules.diffusionmodules.openaimodel.UNetModel
  target: latent_diffusion.ldm.models.diffusion.ddpm.LatentDiffusion
save_path: saved_standard_challenging_context4_eval
